AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Code Pipeline Slack Notifier

Parameters:
  SlackUrl:
    AllowedPattern : ".+"
    Type: String

Resources:
  CPLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lib/index.handler
      Runtime: nodejs8.10
      MemorySize: 128
      Timeout: 10
      CodeUri: ./target/lambda.zip
      Environment:
        Variables:
          SLACK_URL:
            Ref: SlackUrl
      Events:
        CodePipelineEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
              - aws.codepipeline
              detail-type:
              - CodePipeline Pipeline Execution State Change
