AWSTemplateFormatVersion: '2010-09-09'
Description: Code Pipeline Slack Notifier
Parameters:
  SlackUrl:
    AllowedPattern: .+
    Type: String
Resources:
  CPLambda:
    Properties:
      CodeUri: s3://symphonia-oss/sar/code-pipeline-slack-notifier/db3dc355c5885648ff43073b02517c14
      Environment:
        Variables:
          SLACK_URL:
            Ref: SlackUrl
      Events:
        CodePipelineEvent:
          Properties:
            Pattern:
              detail-type:
              - CodePipeline Pipeline Execution State Change
              source:
              - aws.codepipeline
          Type: CloudWatchEvent
      Handler: lib/index.handler
      MemorySize: 128
      Runtime: nodejs8.10
      Timeout: 10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
